server:
    port: 8280

spring:

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:8306/micro-bankservice
        username: micro-bankservice
        password: micro-bankservice

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    rabbitmq:
        port: 8672
        username: rabbit
        password: rabbit

    jackson:
        default-property-inclusion: non_empty

axon:
    serializer:
        general: jackson
    # Si activamos esta propiedad, los eventos que se transmiten a través del eventBus interno para hacer el EventSourcing se envarían a través de rabbitmq para que puedan
    # ser procesados por otros sistemas...
    amqp:
        exchange: events.tx
    # De esta forma se activa el commandbus distribuido por jgroups
    distributed:
        enabled: true
        jgroups:
            bind-addr: 127.0.0.1
            bind-port: 9800
            cluster-name: Axon-CommandBus
            configuration-file: tcp.xml
