version: '3'
services:
    db-client:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-client
            MYSQL_USER: micro-client
            MYSQL_PASSWORD: micro-client
        ports:
            - "6306:3306"
    db-account:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-account
            MYSQL_USER: micro-account
            MYSQL_PASSWORD: micro-account
        ports:
            - "7306:3306"
    db-bankservice:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-bankservice
            MYSQL_USER: micro-bankservice
            MYSQL_PASSWORD: micro-bankservice
        ports:
            - "8306:3306"

    db-query:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-query
            MYSQL_USER: micro-query
            MYSQL_PASSWORD: micro-query
        ports:
            - "9306:3306"
    rabbit:
        image: rabbitmq:3.7-management
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "5672:5672"
            - "15672:15672"
