version: '3'
services:
    db-events:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-events
            MYSQL_USER: micro-events
            MYSQL_PASSWORD: micro-events
        ports:
            - "6306:3306"
    db-query:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro-query
            MYSQL_USER: micro-query
            MYSQL_PASSWORD: micro-query
        ports:
            - "7306:3306"
    rabbit:
        image: rabbitmq:3.7-management
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "5672:5672"
            - "15672:15672"
