version: '3'
services:
    db:
        image: mysql:8.0.16
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: micro
            MYSQL_USER: micro
            MYSQL_PASSWORD: micro
        ports:
            - "6306:3306"
    rabbit:
        image: rabbitmq:3.7-management
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "5672:5672"
            - "15672:15672"
