server:
    port: 8080

spring:

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:6306/micro
        username: micro
        password: micro

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    rabbitmq:
        port: 5672
        username: rabbit
        password: rabbit

    jackson:
        default-property-inclusion: non_empty

axon:
    serializer:
        events: jackson
        general: jackson
        messages: jackson
#    Si activamos esta propiedad, los eventos que se transmiten a través del eventBus interno para hacer el EventSourcing se envarían a través de rabbitmq para que puedan
#    ser procesados por otros sistemas...
#    amqp:
#        exchange: events.tx
