server:
    port: 8180

spring:

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:7306/micro-account
        username: micro-account
        password: micro-account

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    rabbitmq:
        port: 8672
        username: rabbit
        password: rabbit

    jackson:
        default-property-inclusion: non_empty

axon:
    serializer:
        general: jackson
    # Si activamos esta propiedad, los eventos que se transmiten a través del eventBus interno para hacer el EventSourcing se envarían a través de rabbitmq para que puedan
    # ser procesados por otros sistemas... es la manera de hacer sagas coreografiadas
    #amqp:
    #    exchange: events.tx
    # De esta forma se activa el commandbus distribuido por jgroups, es la manera de hacer sagas coordinadas
    distributed:
        enabled: true
        jgroups:
            bind-addr: localhost
            bind-port: 8800
            cluster-name: Axon-CommandBus
            configuration-file: tcp.xml
logging:
    level:
        org:
            jgroups: DEBUG
